version: '3.8'
services:
  db:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes: 
      - db:/var/lib/msql
  app:

volumes:
  db:
    driver: local